In [1]:
import numpy
grid=[[3,0,6,5,0,8,4,0,0], 
      [5,2,0,0,0,0,0,0,0], 
      [0,8,7,0,0,0,0,3,1], 
      [0,0,3,0,1,0,0,8,0], 
      [9,0,0,8,6,3,0,0,5], 
      [0,5,0,0,9,0,6,0,0], 
      [1,3,0,0,0,0,2,5,0], 
      [0,0,0,0,0,0,0,7,4], 
      [0,0,5,2,0,6,3,0,0]] 
def main(grid):
    if(solve(grid)):
        return(numpy.array(grid))
    return("Sorry")

def solve(arr):
    l=[0,0]
    if(not empty(arr,l)):
        return(True)
    row=l[0]
    col=l[1]
    for i in range(1,10):
        if(safe(arr,row,col,i)):
            arr[row][col]=i
            if(solve(arr)):
                return(True)
            arr[row][col]=0
    return(False)
def empty(arr,l):
    for i in range(9):
        for j in range(9):
            if(arr[i][j]==0):
                l[0]=i
                l[1]=j
                return(True)
    return(False)

def safe(arr,row,col,num):
    for i in range(9):
        if(arr[row][i]==num):
            return(False)
        if(arr[i][col]==num):
            return(False)
    row=row - row%3
    col=col - col%3
    for i in range(3):
        for j in range(3):
            if(arr[i+row][j+col]==num):
                return(False)
    return(True)

print(main(grid))

[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [4 8 7 6 2 9 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [9 7 4 8 6 3 1 2 5]
 [8 5 1 7 9 2 6 4 3]
 [1 3 8 9 4 7 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]


In [ ]:
3 1 6 5 7 8 4 9 2
5 2 9 1 3 4 7 6 8
4 8 7 6 2 9 5 3 1
2 6 3 4 1 5 9 8 7
9 7 4 8 6 3 1 2 5
8 5 1 7 9 2 6 4 3
1 3 8 9 4 7 2 5 6
6 9 2 3 5 1 8 7 4
7 4 5 2 8 6 3 1 9