In [12]:
import numpy
n=int(input())
brr=list(map(int,input().split()))
arr=[[0 for i in range(n+1)] for j in range(len(brr))]
for j in range(len(brr)):
    p=1
    for i in range(1,n+1):
        if(j==0 and brr[0]*p==i):
            arr[j][i]=i
            p+=1
        elif(j>0):
            if(brr[j]*p==i):
                arr[j][i]=p
                p+=1
            elif(brr[j]<i):
                arr[j][i]=min(arr[j][i-brr[j]]+1,arr[j-1][i])
            elif(brr[j]*p>i):
                arr[j][i]=arr[j-1][i]
print(numpy.array(arr))
print(arr[j][i])
ans=[]
while(i!=0 and j!=0):
    if(arr[j][i]!=arr[j-1][i]):
        ans.append(brr[j])
        i-=brr[j]
    j-=1
print(ans)
        

11
1 5 6 8
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  1  2  3  4  5  2  3]
 [ 0  1  2  3  4  1  1  2  3  4  2  2]
 [ 0  1  2  3  4  1  1  2  1  2  2  2]]
2
[6, 5]


In [34]:
n=13
brr=[7,2,3,6]
arr=[float("inf") for i in range(n+1)]
arr[0]=0
for i in brr:
    j=i
    while(j<n+1):
        if(min(arr[i],1+arr[j-i])!=float("inf")):
            p=arr[j]
            arr[j]=min(arr[j],1+arr[j-i])
        j+=1

print(arr)

[0, inf, 1, 1, 2, 2, 1, 1, 2, 2, 2, 3, 2, 2]
