In [4]:
import numpy
le=[1,2,3,4]
val=[2,5,7,8]
total=5
arr=[[0 for i in range(total+1)] for i in range(len(le)+1)]
for i in range(1,len(le)+1):
    for j in range(total+1):
        if(i==1):
            arr[i][j]=j*val[0]
        elif(j<le[i-1]):
            arr[i][j]=arr[i-1][j]
        else:
            arr[i][j]=max(arr[i-1][j],arr[i][j-le[i-1]]+val[i-1])
print(numpy.array(arr))
ans=[]
while(i!=0 and j!=0):
    if(arr[i][j]==arr[i-1][j]):
        i-=1
    else:
        ans.append(le[i-1])
        j-=le[i-1]
print(ans)
        

[[ 0  0  0  0  0  0]
 [ 0  2  4  6  8 10]
 [ 0  2  5  7 10 12]
 [ 0  2  5  7 10 12]
 [ 0  2  5  7 10 12]]
[2, 2, 1]
