In [7]:
import numpy
S=input()
arr=[[0 for i in range(len(S))] for i in range(len(S))]
for gap in range(len(S)):
    for i in range(len(S)-gap):
        j=i+gap
        if(i==j):
            arr[i][j]=1
        elif(S[i]==S[j]):
            arr[i][j]=2+arr[i+1][j-1]
        else:
            arr[i][j]=max(arr[i][j-1],arr[i+1][j])
print(numpy.array(arr))
    

agbdba
[[1 1 1 1 3 5]
 [0 1 1 1 3 3]
 [0 0 1 1 3 3]
 [0 0 0 1 1 1]
 [0 0 0 0 1 1]
 [0 0 0 0 0 1]]
