In [13]:
import numpy
brr=list(map(int,input().split()))
n=len(brr)
arr=[[0 for i in range(len(brr))] for i in range(len(brr))]
for gap in range(2,len(d)+1):
    for i in range(len(brr)-gap):
        j=i+gap
        arr[i][j]=float("inf")
        for k in range(i,j):
            temp=arr[i][k]+arr[k][j]+brr[i]*brr[j]*brr[k]
            if(temp<arr[i][j]):
                arr[i][j]=temp
print(numpy.array(arr))

1 2 3 4
[[ 0  0  6 18]
 [ 0  0  0 24]
 [ 0  0  0  0]
 [ 0  0  0  0]]
