In [14]:
import numpy
a=input()
b=input()
arr=[[0 for i in range(len(a)+1)] for j in range(len(b)+1)]
for i in range(len(a)+1):
    arr[0][i]=i
for j in range(1,len(b)+1):
    arr[j][0]=j
for i in range(1,len(b)+1):
    for j in range(1,len(a)+1):
        if(b[i-1]==a[j-1]):
            arr[i][j]=arr[i-1][j-1]
        else:
            arr[i][j]=min(arr[i][j-1],arr[i-1][j],arr[i-1][j-1])+1
print(numpy.array(arr))
ans=[]
while(i!=0 and j!=0):
    if(arr[i][j]==arr[i-1][j-1]+1):
        ans.append(a[j-1])
        i-=1
        j-=1
    else:
        mn=min(arr[i-1][j],arr[i][j-1])
        if(mn==arr[i-1][j-1]):
            i-=1
        else:
            j-=1
print(ans)

abcdef
azced
[[0 1 2 3 4 5 6]
 [1 0 1 2 3 4 5]
 [2 1 1 2 3 4 5]
 [3 2 2 1 2 3 4]
 [4 3 3 2 2 2 3]
 [5 4 4 3 2 3 3]]
['f', 'b']
