In [14]:
brr=list(map(int,input().split()))
cost=list(map(int,input().split()))
arr=[[0 for i in range(len(brr))] for i in range(len(brr))]
for gap in range(len(brr)):
    for i in range(len(brr)-gap):
        j=i+gap
        if(i==j):
            arr[i][j]=cost[i]
        else:
            arr[i][j]=float("inf")
        summ=sum(cost[i:j+1])
        for k in range(i,j):
            if(k==i):
                temp=summ+arr[i+1][j]
            elif(k==j):
                temp=summ+arr[i][j-1]
            else:
                temp=summ+arr[k+1][j]+arr[i][k-1]
            if(temp<arr[i][j]):
                arr[i][j]=temp
print(numpy.array(arr))
            

10 12 20 35 46
34 8 50 21 16
[[ 34  50 176 184 232]
 [  0   8 108 108 156]
 [  0   0  50  92 140]
 [  0   0   0  21  53]
 [  0   0   0   0  16]]
