In [10]:
import numpy
n=int(input())
brr=list(map(int,input().split()))

11
2 3 7 8 10
[[1 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 1 1 0 0 0 0 0 0 0 0]
 [1 0 1 1 0 0 0 0 0 0 0 0]
 [1 0 1 1 0 0 0 0 0 0 0 0]
 [1 0 1 1 0 0 0 0 0 0 0 0]]


In [26]:
arr=[[0 for i in range(n+1)] for i in range(len(brr))]
for i in range(len(brr)):
    arr[i][0]=1
arr[0][brr[0]]=1
for i in range(1,len(brr)):
    for j in range(1,(n+1)):
        if(brr[i]>j):
            arr[i][j]=arr[i-1][j]
        elif(brr[i]<=j):
            if(arr[i-1][j]==1):
                arr[i][j]=1
            elif(arr[i-1][j-brr[i]]==1):
                arr[i][j]=1
            else:
                arr[i][j]=0
print(numpy.array(arr))
ans=[]
while(i!=0 and j!=0):
    if(arr[i][j]!=arr[i-1][j]):
        ans.append(brr[i])
        j-=brr[i]
    i-=1
print(ans)

[[1 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 1 1 0 1 0 0 0 0 0 0]
 [1 0 1 1 0 1 0 1 0 1 1 0]
 [1 0 1 1 0 1 0 1 1 1 1 1]
 [1 0 1 1 0 1 0 1 1 1 1 1]]
[8, 3]
